##===- lib/Makefile ----------------------------------------*- Makefile -*-===##
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
LEVEL = ..

include $(LEVEL)/Makefile.config

PARALLEL_DIRS := Target

include $(LEVEL)/Makefile.common

