#===-- Makefile.common - Common make rules for LLVM --------*- Makefile -*--===#
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.

# Configuration file to set paths specific to local installation of LLVM
ifndef LLVM_OBJ_ROOT
include $(LEVEL)/Makefile.config
else
include $(LLVM_OBJ_ROOT)/Makefile.config
endif

# Include all of the build rules used for making LLVM
include $(LLVM_SRC_ROOT)/Makefile.rules
